library(tidyverse)
library(gtrendsR)
library(trendecon)
library(tsbox)
library(openxlsx)
library(corrr)
library(lubridate)

proc_keyword_init("arbeitslos", "DE")
trendecon:::proc_keyword_latest("arbeitslos", "DE")
proc_index("arbeitslos", "DE", "arbeitslos_ind")
getwd()
